mov_cam_node:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 45.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
    image_width: 1280
    image_height: 960
    camera_name: "test_camera"
    camera_info_url: "package://marker_arm/params/mov_camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1
