bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: fix_base
    robot_base_frame: base_footprint
    odom_topic: /odom
    enable_groot_monitoring: true
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_bt_xml_filename: ""
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_rate_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01

    odom_topic: "odom"
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 500.0

    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 3.14
      stateful: true

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.0
      lookahead_dist: 0.6
      min_lookahead_dist: 0.1
      max_lookahead_dist: 0.3
      lookahead_time: 0.5
      rotate_to_heading_angular_vel: 0.35
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.3
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.15
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 1.2
      max_robot_pose_search_dist: 10.0
      use_interpolation: false

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: true

      update_frequency: 5.0
      publish_frequency: 5.0

      # global_frame: odom
      global_frame: fix_base
      robot_base_frame: base_footprint
      use_sim_time: false
      rolling_window: true
      # width: 8
      # height: 8
      width: 15
      height: 15
      resolution: 0.05
      robot_radius: 0.1

      plugins: ["inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        # cost_scaling_factor: 0.5
        # inflation_radius: 1.0 # // >= max_lookahead_dist
        # cost_scaling_factor: 0.3
        # inflation_radius: 1.0 # // >= max_lookahead_dist
        cost_scaling_factor: 3.0
        inflation_radius: 0.35 # // >= max_lookahead_dist

  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

global_costmap:
  global_costmap:
    ros__parameters:
      # [from] without a map
      # always_send_full_costmap: true
      always_send_full_costmap: false

      update_frequency: 5.0
      publish_frequency: 5.0

      width: 20
      height: 20
      lethal_cost_threshold: 250
      origin_x: -10.0
      origin_y: -10.0
      # [to] without a map

      global_frame: fix_base
      # global_frame: odom

      robot_base_frame: base_footprint
      # robot_base_frame: center_link
      use_sim_time: false
      robot_radius: 0.1
      # resolution: 0.01  # for map capture
      resolution: 0.05
      plugins: ["inflation_layer"] # Order of the layers matters!!!!
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 3.0
        inflation_radius: 0.35 # // >= max_lookahead_dist

  global_costmap_client:
    ros__parameters:
      use_sim_time: false
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

robot_state_publisher:
  ros__parameters:
    use_sim_time: false
