omo_r1mini_mcu_node:
  ros__parameters:
    port:
      name: "/dev/ttyMCU"
      baudrate: 115200

    wheel:
      separation: 0.17
      radius: 0.0335

    motor:
      gear_ratio: 21.3
      max_lin_vel_x: 0.6
      max_ang_vel_z: 7.06

    sensor:
      enc_pulse: 1440.0
      use_gyro: false

    odometry:
      odom_publish: true
      tf_publish: true
      topic_name: "/omo_rob/wheel_odom"
      frame_id: "odom"
      child_frame_id: "base_footprint"

# diff_drive_controller:
#   ros__parameters:
#     odometry:
#       odom_publish: false
#       frame_id: "odom"
#       child_frame_id: "base_footprint"

