teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.12
    scale_linear_turbo:
      x: 0.12

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.35
    scale_angular_turbo:
      yaw: 0.35

    require_enable_button: false
    enable_button: 5  # R1
    enable_turbo_button: 7  # R2
# https://github.com/Ar-Ray-code/ps_ros2_common
